name: Dependent Job Example

on: ['push']

jobs:
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
     - name: JOB1
       run: echo "Hellow"
  job1:
    runs-on: ubuntu-latest
    steps:
     - name: JOB2
       run: echo "World"