on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"  
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Show Server Time
        run: echo "The current Server Time is $(date)"
